### ISSUE TITLE
how should I update the Slack teams post? What scenarios do we consider?

### ISSUE THREAD

**Issue by gotoplanb** [Mobiquity/team-stanton#12]
* [x] where do private messages go?
* [x] how do I call people?

**Comment by kredmyer** [comment]
Regarding private messaging (I think these are called DMs in Slack vernacular), I think this setup is a little unintuitive.

If there is any overlap with team members, then you will be able to send them individual messages through multiple outlets.  The situation occurs where someone may be confused where to contact a person for what reasons - is it okay to talk about a specific project with a team member on MobDev, or should you do it in the project team Slack itself?   The distinction is mostly arbitrary and while not a terribly big deal is messy in my opinion.

The only solution to his, I think, are user-instated "rules" about where to talk about what with whom - which wouldn't be a problem with one Slack setup of everyone in the company (see: what MobDev currently is).  This also may pose a problem for the proposed archiving solution if someone is uninformed or simply doesn't abide by unspoken rules.  There may be disagreement as to what those rules are or should be (which by principle would be kind of fuzzy to establish in the first place - what constitutes work-related chat and otherwise is different for everyone and slip-ups would inevitably occur), which could lead to the latter case of misinformation and messy/scattered chat history.

**Comment by gotoplanb** [comment]
Updated post to cover private messages and calls.
